sudo: required
services: 
  - docker

before_install:
  - docker build -t rodriggj/frontend -f Dockerfile.dev .

script: 
  - docker run -e CI=true rodriggj/frontend npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Testdockerapp"
  env: "Testdockerapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-633951591197"
  bucket_path: "Testdockerapp"
  on: 
    branch: master
  access_key_id: $access_key_id
  secret_access_key: 
    secure: "$secret_access_key"